window.COSME_SLOT_I18N = window.COSME_SLOT_I18N || {};
window.COSME_SLOT_I18N.en = {
  start: "START",
  swipeHint: "Swipe up to spin",
  soldOut: "Today's prizes are sold out",
  admin: "Admin",
  back: "Back",
  lose: "Too bad!",
  enterPin: "Enter 4-digit PIN",
  unlock: "Unlock",
  close: "Close",
  summary: "Summary",
  totalPlay: "Total Plays",
  totalWin: "Total Wins",
  totalLose: "Total Misses",
  stockLeft: "Total Stock Left",
  rankTable: "Prize Breakdown",
  hourly: "Hourly Plays",
  settings: "Settings",
  actions: "Data Actions",
  save: "Save Settings",
  addPrize: "Add Prize Tier",
  downloadCsv: "Download CSV",
  resetData: "Reset Data",
  hour: "Hour",
  playCount: "Plays",
  rank: "Rank",
  winCount: "Wins",
  stock: "Stock",
  probability: "Probability(%)",
  themeColor: "Theme Color",
  backgroundColor: "Background Color",
  accentColor: "Accent Color",
  brandName: "Brand Name",
  reelSymbols: "Reel symbol IDs (comma separated)",
  pinError: "Incorrect PIN",
  saveOk: "Settings saved",
  saveNg: "Failed to save settings",
  badProbability: "Total probability must be 100% or less",
  badStock: "Stock must be an integer >= 0",
  badSymbol: "Each prize tier needs exactly 3 symbols",
  resetConfirm: "Reset all logs, settings, and inventory. Continue?",
  resetDone: "Data reset complete",
  footer: "Offline event operation mode"
};
