window.COSME_SLOT_I18N = window.COSME_SLOT_I18N || {};
window.COSME_SLOT_I18N.ja = {
  start: "スタート",
  swipeHint: "上方向へスワイプしても回せます",
  soldOut: "本日の景品はなくなりました",
  admin: "管理",
  back: "もどる",
  lose: "残念！",
  enterPin: "4桁PINを入力",
  unlock: "解除",
  close: "閉じる",
  summary: "集計サマリー",
  totalPlay: "総プレイ回数",
  totalWin: "総当選数",
  totalLose: "はずれ数",
  stockLeft: "残在庫合計",
  rankTable: "ランク別集計",
  hourly: "時間帯別プレイ数",
  settings: "設定",
  actions: "データ操作",
  save: "設定を保存",
  addPrize: "ランク追加",
  downloadCsv: "CSVダウンロード",
  resetData: "データリセット",
  hour: "時間",
  playCount: "プレイ数",
  rank: "ランク",
  winCount: "当選数",
  stock: "在庫",
  probability: "確率(%)",
  themeColor: "テーマカラー",
  backgroundColor: "背景色",
  accentColor: "アクセントカラー",
  brandName: "ブランド名",
  reelSymbols: "リールシンボルID（カンマ区切り）",
  pinError: "PINが正しくありません",
  saveOk: "設定を保存しました",
  saveNg: "設定保存に失敗しました",
  badProbability: "確率合計は100%以下にしてください",
  badStock: "在庫は0以上の整数で入力してください",
  badSymbol: "各ランクのシンボルは3つ必要です",
  resetConfirm: "集計ログ・設定・在庫をすべてリセットします。よろしいですか？",
  resetDone: "データをリセットしました",
  footer: "※ イベント運用用（オフライン動作）"
};
