window.COSME_SLOT_I18N = window.COSME_SLOT_I18N || {};
window.COSME_SLOT_I18N.ko = {
  start: "시작",
  swipeHint: "위로 스와이프해도 시작됩니다",
  soldOut: "오늘의 경품이 모두 소진되었습니다",
  admin: "관리",
  back: "돌아가기",
  lose: "아쉬워요!",
  enterPin: "4자리 PIN 입력",
  unlock: "해제",
  close: "닫기",
  summary: "집계 요약",
  totalPlay: "총 플레이 수",
  totalWin: "총 당첨 수",
  totalLose: "꽝 수",
  stockLeft: "총 남은 재고",
  rankTable: "등급별 통계",
  hourly: "시간대별 플레이 수",
  settings: "설정",
  actions: "데이터 작업",
  save: "설정 저장",
  addPrize: "등급 추가",
  downloadCsv: "CSV 다운로드",
  resetData: "데이터 초기화",
  hour: "시간",
  playCount: "플레이 수",
  rank: "등급",
  winCount: "당첨 수",
  stock: "재고",
  probability: "확률(%)",
  themeColor: "테마 색상",
  backgroundColor: "배경 색상",
  accentColor: "강조 색상",
  brandName: "브랜드명",
  reelSymbols: "릴 심볼 ID (쉼표 구분)",
  pinError: "PIN이 올바르지 않습니다",
  saveOk: "설정이 저장되었습니다",
  saveNg: "설정 저장에 실패했습니다",
  badProbability: "확률 합계는 100% 이하여야 합니다",
  badStock: "재고는 0 이상의 정수여야 합니다",
  badSymbol: "각 등급은 3개의 심볼이 필요합니다",
  resetConfirm: "로그, 설정, 재고를 모두 초기화합니다. 계속할까요?",
  resetDone: "데이터가 초기화되었습니다",
  footer: "오프라인 이벤트 운영 모드"
};
